-- MySQL Script generated by MySQL Workbench
-- Sun Mar 31 13:36:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mymdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mymdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mymdb` DEFAULT CHARACTER SET utf8 ;
USE `mymdb` ;

-- -----------------------------------------------------
-- Table `mymdb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymdb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mymdb`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `is_admin` TINYINT NOT NULL,
  `displayname` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymdb`.`Genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymdb`.`Genres` ;

CREATE TABLE IF NOT EXISTS `mymdb`.`Genres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `genre_UNIQUE` (`genre` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymdb`.`Movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymdb`.`Movies` ;

CREATE TABLE IF NOT EXISTS `mymdb`.`Movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `releaseDate` DATE NOT NULL,
  `description` TINYTEXT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `FK_GENRE_idx` (`genre_id` ASC),
  CONSTRAINT `FK_GENRE`
    FOREIGN KEY (`genre_id`)
    REFERENCES `mymdb`.`Genres` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymdb`.`Images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymdb`.`Images` ;

CREATE TABLE IF NOT EXISTS `mymdb`.`Images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NULL,
  `filename` VARCHAR(75) NOT NULL,
  `text` VARCHAR(100) NOT NULL,
  `alttext` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`, `movie_id`),
  INDEX `FK_Movies_idx` (`movie_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `FK_Movies`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mymdb`.`Movies` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mymdb`.`Reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mymdb`.`Reviews` ;

CREATE TABLE IF NOT EXISTS `mymdb`.`Reviews` (
  `user_id` INT NOT NULL,
  `movie_id` INT NOT NULL,
  `review` TINYTEXT NOT NULL,
  `starrating` INT NULL,
  `created` TIMESTAMP NOT NULL,
  `subject` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`movie_id`, `user_id`),
  INDEX `FK_user_id_idx` (`user_id` ASC),
  CONSTRAINT `FK_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `mymdb`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_movie_id`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mymdb`.`Movies` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
